### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by DennyZen** [hkaanengin/spark-structured-streaming#23]
I am getting 
`/usr/bin/env: ‘bash\r’: Permission denied`
error in airflow-kafka-spark-webserver-1
 when trying to run it on my windows system..
windows cant find this path ?.. thats why , right ?

**Comment by hkaanengin** [comment]
Hello @DennyZen,
I believe you re having this issue while trying to create webserver image on docker. I had a similar issue on my MacOS. If you can change [Webserver command variable](https://github.com/hkaanengin/spark-structured-streaming/blob/main/docker-compose-infra.yml#L231) to **bash -c "chmod +x /opt/airflow/script/entrypoint.sh"** from **webserver**, your problem would be fixed.

Webserver image should look something like this(Check **command**):

webserver:
    image: apache/airflow:2.6.0-python3.9
    command: bash -c "chmod +x /opt/airflow/script/entrypoint.sh"
    entrypoint: ['/opt/airflow/script/entrypoint.sh']
    depends_on:
      ...

Hope this helps to solve your problem. If not, please share a screenshot of the error along with the code of your docker compose, so I can assist you further.

**Comment by hkaanengin** [comment]
Hello @DennyZen ,
I assume your issue is resolved since I got no reply from you. If my presented fix doesn't solve your problem, please re-open it with more detailed info(such with screenshots, logs etc). I am closing this issue now.
